profile_app/urls.py
from django.conf.urls import url
from django.urls import path
from .views import profile

urlpatterns = [
    path('', profile, name='profile'),
]

status_form/urls.py
from django.conf.urls import url
from django.urls import path
from .views import status, add_status

urlpatterns = [
    path('', status, name='status'),
    path('add_status', add_status, name='add_status'), # for form submission
]

story_6_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('status_form.urls', 'story-6-status'), namespace='story-6-status')),
    path('profile', include('profile_app.urls')),
]

profile_app/models.py
from django.db import models

# Create your models here.

status_form/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime

# Create your models here.

class StatusUpdate(models.Model):
    message = models.CharField(max_length=300)
    date = models.DateTimeField(default=timezone.now)

status_form/forms.py
from django import forms

class Status_Update_Form(forms.Form):
    
    error_messages = {
        'required': 'Please fill this input',
    }
    
    message_attrs = {
        'class': 'form-control form-group',
        'placeholder': 'Enter new status message'
    }

    message = forms.CharField(label='Status message', required=True, max_length=300, widget=forms.TextInput(attrs=message_attrs))

profile_app/views.py
from django.shortcuts import render

# Create your views here.

response = {}
def profile(request):
	response['profile_name'] = 'Kevin Christian Chandra'
	response['npm'] = '1706039976'
	return render(request, 'profile.html', response)

status_form/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .forms import Status_Update_Form
from .models import StatusUpdate

# Create your views here.

response = {}
def status(request):
	response['title'] = 'Add Status'
	response['status_update_form'] = Status_Update_Form
	response['status_updates'] = StatusUpdate.objects.all().values().order_by('date').reverse()
	return render(request, 'status.html', response)

def add_status(request):
	# create a form instance and populate it with data from the request:
	form = Status_Update_Form(request.POST or None)

	# check whether method is a POST and whether the form is valid
	if(request.method == 'POST' and form.is_valid()):
		response['message'] = request.POST['message']
		status = StatusUpdate(message=response['message'])
		status.save()
	return HttpResponseRedirect('/')

profile_app/templates/profile.html
<!DOCTYPE html>
<html>
    <head>
        <title>PPWLab - My Profile</title>
    </head>

    <body>
        <h1>Halo! Nama saya {{profile_name}}! Saya adalah mahasiswa Fasilkom Yu-Ai!</h1>
        <hr>
        <h3>NPM saya adalah {{npm}}.</h3>
    </body>
</html>

status_form/templates/status.html
<!DOCTYPE html>
<html>
{% load static %}
    <head>
        <title>PPWLab - My Status</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=yes">

    	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'Lab3.css' %}">
    	<style type="text/css">
            /** {
                border-style: solid;
            }*/
    	</style>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </head>

    <body>
    	<!-- from bootstrap -->
    	<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="navBar">
            <img class="rounded-circle" id="kakPeweLogo" src="{% static 'img/Kak-Pewe.jpg' %}">
            <a class="navbar-brand" id="navBarBrand" href="#"><h3>PPWLAB - MY STATUS</h3></a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </nav>

        <!-- main card -->
        <div class="card" id="card1">
            <div class="card-body">
                <div>
                    <h1>Hello, Apa kabar?</h1>
                    <hr>
                    <h2 id="name">Post new status!</h2>
                </div>

                <form method="POST" action="{% url 'story-6-status:add_status' %}">
                    {% csrf_token%}
                    {{status_update_form}}

                    <button id = "submitPost" type="submit" class="btn btn-success">Post</button>
                </form>
            </div>
        </div>

        <div id="card2">
    		<div class="card header-card">
                <div class="card-body header-card-body">
                    <h4 id="about">My Status</h4>
                </div>
            </div>

            <div class="card">
                <div class="card-body">
                    <table class="table table-hover">
                        <tbody>
                            {% for StatusUpdate in status_updates %}
                            <tr>
                            <td scope="row">{{StatusUpdate.date}}</td>
                            <td>{{StatusUpdate.message}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </body>
</html>